package com.nick.cards.domain.security.models.request;

import com.nick.cards.domain.security.annotations.Password;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;

@Getter
@Setter
@Builder
@ApiModel(value = "ResetPasswordRequest", description = "Model to submit reset password details")
public class ResetPasswordRequest {
    @NotBlank(message = "please provide a valid token")
    @ApiModelProperty(position = 1, example = "6cce7d66-20cd-4dac-bf90-07420b1eea97", required = true, dataType = "String", notes = "Token from generated by the system")
    private String token;

    @NotBlank(message = "please provide a valid password")
    @Password
    @Size(min = 10, max = 100)
    @ApiModelProperty(position = 3, example = "myPassword", required = true, dataType = "String", notes = "Use your preferred password here")
    private String password;

}