version: '3.9'
services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=card_user
      - MYSQL_DATABASE=card_db
      - MYSQL_DATABASE=card_db_test
